# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9527
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 600
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# fastDFS文件上传配置
fdfs:
  domain: http://47.93.58.109
  soTimeout: 3000
  connectTimeout: 2000
  trackerList: 47.93.58.109:22122

#支付宝支付参数配置
alipay:
  #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  appId: 2021003125631214
  #商户私钥，您的PKCS8格式RSA2私钥
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChgsGegBm+mycTT1LN1ogbaNUgqt1z0VGwCMf6AnZ7SWL4ZY+D2HS9zydzAuYtgoXQz4aCjys2eTBVfdmTOYPBMTAbCwULVal2fYIJHQCWPCGWcatTZj00dFY1BQDt60757qS0VooUJKrrRdzl/YrbmMxmBtv2HXMp7VgY26vXqjUIxUKWVmkRRI5l+rn5Zk0ZdqPhowvPz01nuTE6zCObQVojKDlgLSQJOHkuX3d/ARTPkm7+OfwHb93LZ1FIJx3ah5fSKnqprQaKvS3o5NYXITxZPwZiOaaw+2b1dAVTWa+ZPz0BX5PMe8Dz7/erFMNG6hLw/eN1AY+unjwlMLhZAgMBAAECggEAN6n0ByeJN+sLRZlyJWUJ1cCEq9SXrEH5EF2GZoEQyp7ZUFjYZI1mdsB9jSLzp72zVusfJcIoF4cfBGfyY85PvXaxaLCclXJ5jE/nUDLBsAWbYdldPcof0ANEbtOBpX4S4wq/kzO8NQMKMToLzuxaPiLkV0mH58PwnAOj+DVFfXcsNndAchOWNn1jKWb6sv05j/zFA3A+KD2tLko7LMJV4GuVEUT2DU1ocar6Lu0e1AJEh1BGyM0MeHnSvAvxlFKJCEuIELSMTeBcwRI5jrA+iwcM/2VDTpOTFsvVJtRNsJDItybkSl8IyqTXsVelEx7RWkuTErgZKBeA23GbLBx//QKBgQDfWesrUnojmlkt1NHUJY2WvQagOHwEAIs4ibeqIhCYQsx4s5FS9cQNJ6KzMIfMMrKALdxSVNFH/23CRp+TVeLfQnCUZBVVsO8cNRJGtdkBgI0RDQX7TllEpxW0kkyshLM0UO6Z3lzNciuLUoElhMO+FPZgeyF/2c4GJzfxH1se7wKBgQC5HrCqkZmC1kbKHHa6FC3NKZ+ph+JocuKAsuX1UcVF4eu+3ngdB++Xn2mkA3MGwvjsf0rYqDturyh1jpxE6HYfB+1M5N3nEnZeSZMScH1k3ciFN12Kvr+ey7hWxHkjXn7X8xl1Y9N3DYHcFxwIcST7hqbCEF0H5q2PI8qjC6QdNwKBgFdrR1t+faW/vNXubW4+gIuWUqiVUxzx5Yvsg0GI8bvWsVcw2VmCLgkEEW9XOF+ZHDqFOK3U2tD2TcxzffPZ8uF1jMDX523RwdTlhNC+TkCDQzOASG4TPWdcimdRt8bybX21i54X5XTYEekHEttPepnEdKZQq0zyP+wyn3e10SFrAoGBAIrvyMJLwr5a2gho8obYDEQWAFn5vWiNCQh0vHixZXD8jbXUPKv1P9I5d8z8NcGWZcMCCoevQ+PfnGsWnJxvJ/BEP8rdXtpFlgdQCwzk1of0mMG6+v7eCO1Ckti0XwK3slWbg7kCMj0BKzynL4f6ezo4JkIyi9AZRpvOzhAu9X5jAoGBAIOci2ShUMl2dRr/1aGEiSU7LHkcwGh5eIuFnQG39F2ShrfHZ5CT8DoFvp6u93EYqPKRkP4iU2o4t1x0V//N5VGhK2f45pSvouKpCqsVEooSSPWClB6OJygZSYGZPmeLIjZLNJ4wyQAwHiZD6KflB6LiKxPwO3E4GQDJqFT/3Jun
  #支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
  #  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqVx4HRM+NYWJIICWi7OU3OcUR5ACcyZ24oSxbXNVQlr3it++wLybRzgVWR9n1vNTiqS34nZm9h9bxnlwqnKu/btWFux9QZJlzd+JEr3Q+VhoXvFRjHJE1EEgn7RkZ8lIUeMAuJ9iO/r9+VwqEL4IbFIaj/ADoCtnYUiXOMlaxHFBh+ckFi8k/xQAJYblwSdjPA0gGbbQbBngNAzjjzGbWobuKdiMDqC/Z91KjLsDvFRpXWYHYtzsDE13OnZvSCuPUbqgQs+4E1/t2qnBhwC9Kao7Ib1hc4hZTf5goBPNTnvb5OCH0jiEjmFnWerB8FMTcji1ikOt1D68bsnR+HWT/QIDAQAB
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoYLBnoAZvpsnE09SzdaIG2jVIKrdc9FRsAjH+gJ2e0li+GWPg9h0vc8ncwLmLYKF0M+Ggo8rNnkwVX3ZkzmDwTEwGwsFC1Wpdn2CCR0AljwhlnGrU2Y9NHRWNQUA7etO+e6ktFaKFCSq60Xc5f2K25jMZgbb9h1zKe1YGNur16o1CMVCllZpEUSOZfq5+WZNGXaj4aMLz89NZ7kxOswjm0FaIyg5YC0kCTh5Ll93fwEUz5Ju/jn8B2/dy2dRSCcd2oeX0ip6qa0Gir0t6OTWFyE8WT8GYjmmsPtm9XQFU1mvmT89AV+TzHvA8+/3qxTDRuoS8P3jdQGPrp48JTC4WQIDAQAB
  #  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnMtseNzwyIzSq4Zh/y37QYDxSoZNgH3nTizEylXjKYnAv2k5ZfYjbiJtZzYwhw3RnZbBy3Gbgu1BOrU4Yyh1TYcyFh95CHUwxWpg8rilcUaJ8EclzcTmxmnZJsHZSRYvMBbO7iM6Da5m19fS8ORtLlUp3zSRpxza3srP4Zy+7ibEXNVfLzJVOvG74D6LhrL3XCvwV4rUnOgkmW4w0MSqnFwRIko1M4ne+QahsOhn7q2obufU5j7TWFGxFauSI+197e0kdSjAYf1tW9JP2Kxiqc/65fPUGl0Xdw850cHQQipFRzuAf+t27IKY8Ul0IlyRX+LiNCl+6mrTi4DbggBYQQIDAQAB
  #服支付宝网关
  gatewayUrl: https://openapi.alipay.com/gateway.do
  #服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notifyUrl: /prod-api/pay/ali/callback/notify
  #页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  refundUrl: /prod-api/pay/ali/callback/refund

  #正式支付宝网关
  certPath: /home/ruoyi/alipay/appCertPublicKey_2021003125631214.crt
  publicCertPath: /home/ruoyi/alipay/alipayCertPublicKey_RSA2.crt
  rootCertPath: /home/ruoyi/alipay/alipayRootCert.crt
  #本地支付宝网关
#  certPath: D:\alipay\appCertPublicKey_2021003125631214.crt
#  publicCertPath: D:\alipay\alipayCertPublicKey_RSA2.crt
#  rootCertPath: D:\alipay\alipayRootCert.crt

wxpay:
  #公众号appid
  appId: aaaaa
  #商户id
  mchId: 11111111111111
  #支付api安全密钥
  mchKey: 111111111111111111111111111111111
  #  沙箱环境密钥
  #  mchKey: 6ceb9909538b84500dc45774a67c83f2
  signType: MD5
  #支付结果异步回调地址
  notifyUrl: /pay/wx/callback/notify
  #支付结果同步回调地址
  returnUrl: /pay/wx/callback/sync
  #根目录下的证书名称
  certName: apiient_cert.p12cl
  #证书路径
  certPath: classpath:config


